---
- name: Install the mysql rpm from a remote repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm state=present

- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
     - mysql-community-server
     - MySQL-python
     - libselinux-python

- name: Copy the my.cnf file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
   - restart mysql

- name: Start the mysql server
  service: name=mysqld state=started enabled=yes

- name: Getting MySql Temporary Password
  shell:  "grep 'temporary password' /var/log/mysqld.log | awk {'print $11'}"
  register: mysql_temp_password

- name: Display Mysql Temporary Root Password
  debug:
    msg: "{{ mysql_temp_password.stdout }}"
    verbosity: 2

- name: Changing Root Password
  shell: '/usr/bin/mysqladmin -u root -p"{{ mysql_temp_password.stdout }}" password {{ mysql_root_db_pass }}'
  register: changing_root_password
  failed_when:
    - "'error' in changing_root_password.stderr"

- name: Error In changing Root Password | if Error
  debug:
    msg: "{{ changing_root_password.stderr }}"
    verbosity: 2

- name: Removing anonymous user
  mysql_user:
    user: ""
    host: localhost
    state: absent
    login_user: root
    login_password: "{{ mysql_root_db_pass }}"

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_password: "{{ mysql_root_db_pass}}"
    login_user: root

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=~/.my.cnf mode=0600

- name: Create Application Database
  mysql_db: name={{ dbname }} login_password={{ mysql_root_db_pass }} state=present
